import Data.List
import Control.Arrow

elf n [] = ([],[])
elf 0 x = ([],x)
elf n ((a,1):rest) = first (a:) (elf (n-1) rest)
elf n ((a,t):rest) = second ((a,t-1):) (elf (n-1) rest)

solve n t todo work s = step [ c | length work < n, c <- take 1 $ todo \\ (map fst work ++ map snd s) ]
    where step [c] = solve n t (todo \\ [c]) ((c, 61 + fromEnum c - fromEnum 'A'):work) s
          step [] = let (done,work') = elf n work
                    in (done ++) <$> if null work then (t,[]) else solve n (t+1) todo work' $ filter (not . flip elem done . fst) s

solve' n = solve n 0 (sort $ nub $ uncurry (++) $ unzip input) [] input

main = print (snd $ solve' 1, fst $ solve' 5)

input = [
    ('E','Y'),
    ('Y','T'),
    ('I','C'),
    ('G','F'),
    ('C','P'),
    ('B','Q'),
    ('Z','N'),
    ('J','W'),
    ('W','P'),
    ('K','D'),
    ('Q','L'),
    ('V','D'),
    ('O','M'),
    ('A','P'),
    ('M','L'),
    ('R','S'),
    ('D','X'),
    ('X','N'),
    ('P','T'),
    ('F','N'),
    ('S','L'),
    ('U','N'),
    ('T','L'),
    ('N','H'),
    ('L','H'),
    ('N','L'),
    ('X','F'),
    ('P','F'),
    ('P','H'),
    ('B','D'),
    ('V','H'),
    ('X','S'),
    ('Q','O'),
    ('Z','T'),
    ('K','N'),
    ('S','H'),
    ('M','P'),
    ('Q','D'),
    ('R','U'),
    ('J','P'),
    ('P','S'),
    ('V','U'),
    ('R','T'),
    ('F','S'),
    ('D','T'),
    ('E','N'),
    ('J','N'),
    ('J','A'),
    ('K','U'),
    ('V','N'),
    ('V','S'),
    ('U','L'),
    ('F','U'),
    ('I','T'),
    ('J','L'),
    ('E','T'),
    ('T','N'),
    ('I','G'),
    ('R','D'),
    ('E','B'),
    ('X','H'),
    ('P','L'),
    ('Z','J'),
    ('O','L'),
    ('E','H'),
    ('F','T'),
    ('A','F'),
    ('U','H'),
    ('F','H'),
    ('C','W'),
    ('A','L'),
    ('V','M'),
    ('U','T'),
    ('E','P'),
    ('Y','U'),
    ('W','R'),
    ('E','X'),
    ('Q','U'),
    ('I','F'),
    ('V','F'),
    ('V','T'),
    ('R','P'),
    ('B','A'),
    ('S','T'),
    ('M','F'),
    ('Y','F'),
    ('C','K'),
    ('D','S'),
    ('O','S'),
    ('M','U'),
    ('Z','S'),
    ('R','H'),
    ('C','O'),
    ('G','Q'),
    ('Z','D'),
    ('B','N'),
    ('I','H'),
    ('I','P'),
    ('E','J'),
    ('V','L'),
    ('B','U')]
